main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('potatoes/', views.potatoes_index, name='potatoes_index'),
    path('potatoes/<int:potato_id>/', views.potato_detail, name='potato_detail'),
    path('potatoes/create/', views.PotatoCreate.as_view(), name='potatoes_create'),
    path('potatoes/<int:pk>/update/', views.PotatoUpdate.as_view(), name='potatoes_update'),
    path('potatoes/<int:pk>/delete/', views.PotatoDelete.as_view(), name='potatoes_delete'),
    
    path('potatoes/<int:potato_id>/add_cleaning/', views.add_cleaning, name='add_cleaning'),
    
    path('potatoes/<int:potato_id>/assoc_accessory/<int:accessory_id>/', views.assoc_accessory, name='assoc_accessory'),
    path('potatoes/<int:potato_id>/de_assoc_accessory/<int:accessory_id>/', views.de_assoc_accessory, name='de_assoc_accessory'),
    path('potatoes/<int:potato_id>/clear_all_accessories/', views.clear_all_accessories, name='clear_all_accessories'),


    path('accessories/', views.AccessoryList.as_view(), name='accessories_index'),
    path('accessories/<int:pk>/', views.AccessoryDetail.as_view(), name='accessories_detail'),
    path('accessories/create/', views.AccessoryCreate.as_view(), name='accessories_create'),
    path('accessories/<int:pk>/update/', views.AccessoryUpdate.as_view(), name='accessories_update'),
    path('accessories/<int:pk>/delete/', views.AccessoryDelete.as_view(), name='accessories_delete'),
]

potatocollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #add path to the root route
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date

WASHES = (
    ('R', 'Rinse in Sink'), 
    ('S', 'Scrub in Tub'), 
    ('D', 'Deep Soak')
)

# Create your models here.
class Accessory(models.Model):
  name = models.CharField(max_length=50)
  description = models.TextField(max_length=250)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('accessories_detail', kwargs={'pk': self.id})



class Potato(models.Model):
    name = models.CharField(max_length=100)
    birth_place = models.CharField(max_length=100)
    length = models.IntegerField()
    weight = models.IntegerField()
    age = models.IntegerField()
    description = models.TextField(max_length=250)
    accessories = models.ManyToManyField(Accessory)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('potato_detail', kwargs={'potato_id': self.id})


class Cleaning(models.Model):
    date = models.DateField('cleaning date')
    wash = models.CharField(
        max_length=1, 
        choices=WASHES,
        default=WASHES[0][0]
    )
    potato = models.ForeignKey(Potato, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_wash_display()} on {self.date} ({self.potato.name})"

    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Cleaning

class CleaningForm(ModelForm):
  class Meta:
    model = Cleaning
    fields = ['date', 'wash']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Potato, Accessory
from .forms import CleaningForm

# Create your views here.


# Define the home view
def home(request):
  #return HttpResponse('<h1>Hello Potato People!</h1>')
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def potatoes_index(request):
  potatoes = Potato.objects.all()
  return render(request, 'potatoes/potatoes_index.html', {'potatoes': potatoes})

def potato_detail(request, potato_id):
  potato = Potato.objects.get(id=potato_id)
  accessories_potato_doesnt_have = Accessory.objects.exclude(id__in = potato.accessories.all().values_list('id'))
  cleaning_form = CleaningForm()
  return render(request, 'potatoes/potato_detail.html', {
    'potato': potato, 
    'cleaning_form': cleaning_form,
    'accessories': accessories_potato_doesnt_have
  })

class PotatoCreate(CreateView):
  model = Potato
  fields = ['name', 'birth_place', 'length', 'weight', 'age', 'description']

class PotatoUpdate(UpdateView):
  model = Potato
  fields = ['birth_place', 'length', 'weight', 'age', 'description']

class PotatoDelete(DeleteView):
  model = Potato
  success_url = '/potatoes/'

def add_cleaning(request, potato_id):
  # create a model form instance using the data in request.POST
  form = CleaningForm(request.POST)
  # validate that the form is good
  if form.is_valid():
    # can't save to the db until the potato_id is assigned
    new_cleaning = form.save(commit=False)
    # now assign the potato_id
    new_cleaning.potato_id = potato_id
    new_cleaning.save()
  return redirect('potato_detail', potato_id=potato_id)

def assoc_accessory(request, potato_id, accessory_id):
  # Note that you can pass a accessory's id instead of the whole object
  Potato.objects.get(id=potato_id).accessories.add(accessory_id)
  return redirect('potato_detail', potato_id=potato_id)

#removing an accessory
def de_assoc_accessory(request, potato_id, accessory_id):
  # Note that you can pass a accessory's id instead of the whole object
  Potato.objects.get(id=potato_id).accessories.remove(accessory_id)
  return redirect('potato_detail', potato_id=potato_id)

#remove all accessories
def clear_all_accessories(request, potato_id):
  Potato.objects.get(id=potato_id).accessories.clear()
  return redirect('potato_detail', potato_id=potato_id)

class AccessoryList(ListView):
  model = Accessory

class AccessoryDetail(DetailView):
  model = Accessory

class AccessoryCreate(CreateView):
  model = Accessory
  fields = '__all__'

class AccessoryUpdate(UpdateView):
  model = Accessory
  fields = ['name', 'description']

class AccessoryDelete(DeleteView):
  model = Accessory
  success_url = '/accessories/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Potato Collector</h1>
<hr />
<p>Hire the Potato Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Potato Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Potato Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'accessories_create' %}">Add an Accessory</a></li>
          <li><a href="{% url 'accessories_index' %}">View All Accessories</a></li>
          <li><a href="{% url 'potatoes_create' %}">Add a Potato</a></li>
          <li><a href="{% url 'potatoes_index' %}">View All My Potatoes</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2021 Potato Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Welcome to the Potato Collector</h1>

{% endblock %}

main_app/templates/main_app/accessory_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Accessory</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'accessories_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/accessory_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Accessory Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ accessory.name }}</span>
        <p>Description: {{ accessory.description }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'accessories_update' accessory.id %}">Edit</a>
        <a href="{% url 'accessories_delete' accessory.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/accessory_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Accessory</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/accessory_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Accessory List</h1>

{% for accessory in accessory_list %}
  <a href="{% url 'accessories_detail' accessory.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ accessory.name }}</span>
            <p>Description: {{ accessory.description }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/potato_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Potato</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'potato_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/potato_form.html
{% extends 'base.html' %}

{% block content %}

  {% if object %}
    <!-- UpdateView rendering this template -->
    <h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
  {% else %}
    <!-- CreateView rendering this template -->
    <h1>Add Potato</h1>
  {% endif %}

  <!-- Leaving the action empty makes a form post to the same
  url as shown in the address bar -->
  <form action="" method="POST">
    <!-- Django requires the following for security -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs/labels inside of <tr> & <td>s -->
      {{ form }}
    </table>
    <input type="submit" value="Submit" class="btn">
  </form>

  {% if object %}
    <a href="{% url 'potato_detail' object.id %}">Cancel</a>
  {% endif %}

{% endblock %}

main_app/templates/potatoes/potato_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Potato Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
        <div class="card-content">
          <span class="card-title">{{ potato.name }}</span>
          
          <p>Birth Place: {{ potato.birth_place }}</p>

          <p>Length (in): {{ potato.length }}</p>

          <p>Weight (oz): {{ potato.weight }}</p>
          
          {% if potato.age > 12 %}
            <p>Age (wks): {{ potato.age }} (*he's an old fell'r)</p>
          
          {% elif potato.age < 3 %}
            <p>Age (wks): {{ potato.age }} (*he's an young'n)</p>

          {% else %}
            <p>Age (wks): {{ potato.age }}</p>
          
          {% endif %}

          <p>Description: {{ potato.description }}</p>
        
        </div>
        <div class="card-action">
          <a href="{% url 'potatoes_update' potato.id %}">Edit</a>
          <a href="{% url 'potatoes_delete' potato.id %}">Delete</a> 
        </div>
    </div>
  </div>
  <div class="col s6">
    <form method="POST" action="{% url 'add_cleaning' potato.id %}">
      {% csrf_token %}
      {{ cleaning_form.as_p }}
      <input type="submit" class="btn" value="Add Cleaning">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Wash</th></tr>
      </thead>
      <tbody>
        {% for cleaning in potato.cleaning_set.all %}
          <tr>
            <td>{{cleaning.date}}</td>
            <td>{{cleaning.get_wash_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<!-- This is all new markup to be added just above the <script> tag -->
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ potato.name }}'s Accessories</h3>
    {% if potato.accessories.count %}
      {% for accessory in potato.accessories.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              {{ accessory.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'de_assoc_accessory' potato.id accessory.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Remove</button>
            </form>
          </div>
        </div>
      {% endfor %}
      <!-- clear all associated accessories-->
      <div>
        <form action="{% url 'clear_all_accessories' potato.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn">Remove All</button>
        </form>
      </div>
    {% else %}
      <h5>No Accessories :(</h5>
    {% endif %}
  </div>
  <!-- Available toys will come after this line -->
  <div class="col s6">
    <h3>Available Accessories</h3>
    {% if accessories.count %}
      {% for accessory in accessories.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              {{ accessory.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_accessory' potato.id accessory.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{potato.name}} Already Has All Accessories Available</h5>
    {% endif %}
  </div>

</div>





<script>
  const dateEl = document.getElementById('id_date')
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  const selectEl = document.getElementById('id_wash');
  M.FormSelect.init(selectEl);

</script>

{% endblock %}

main_app/templates/potatoes/potatoes_index.html
{% extends 'base.html' %}
{% block content %}

<h1>Potato List</h1>

{% for potato in potatoes %}
  <div class="card">
    <a href="{% url 'potato_detail' potato.id %}">
      <div class="card-content">
        <span class="card-title">{{ potato.name }}</span>
        
        <p>Birth Place: {{ potato.birth_place }}</p>

        <p>Length (in): {{ potato.length }}</p>

        <p>Weight (oz): {{ potato.weight }}</p>
        
        {% if potato.age > 12 %}
          <p>Age (wks): {{ potato.age }} (he's an old fell'r)</p>
        
        {% elif potato.age < 3 %}
          <p>Age (wks): {{ potato.age }} (he's an young'n)</p>

        {% else %}
          <p>Age (wks): {{ potato.age }}</p>
        
        {% endif %}

        <p>Description: {{ potato.description }}</p>
      
      </div>
    </a>
  </div>
{% endfor %}

{% endblock %}